import { promises as fs } from "fs";
import path from "path";

import simpleGit from "simple-git";
import { window, ExtensionContext } from "vscode";

import { getDate, CODERANK_FILENAME } from "../util";

export class Git {
    private constructor(
        private username: string,
        private token: string,
        public repo: string,
        public branch: string | null,
        public coderankDir: string,
        public repoDir: string,
        public remoteCoderankDir: string,
        public remoteCoderankFile: string
    ) {}

    private static async login(
        context: ExtensionContext,
        saveCredentials: boolean
    ): Promise<Git | null> {
        const username = await window.showInputBox({
            prompt: `Enter your GitHub username.${saveCredentials ? " If desired, enable credential saving via `coderank.saveCredentials` for faster access." : ""}`,
            placeHolder: "Username",
            value: (await context.secrets.get("githubUser")) ?? "",
            ignoreFocusOut: true,
        });

        const token = await window.showInputBox({
            prompt: "Enter your GitHub PAT",
            placeHolder: "Personal access token",
            password: true,
            value: (await context.secrets.get("githubPAT")) ?? "",
            ignoreFocusOut: true,
        });

        const repo = await window.showInputBox({
            prompt: "Enter your coderank repo name",
            placeHolder: "Repository name",
            value: (await context.secrets.get("githubRepo")) ?? "",
            ignoreFocusOut: true,
        });

        // Unknown branch name until repo is cloned
        const branch = null;

        if (username && token && repo) {
            const coderankDir = context.globalStorageUri.fsPath;
            const repoDir = path.join(coderankDir, repo);
            const remoteCoderankDir = path.join(repoDir, "coderank");
            const remoteCoderankFile = path.join(remoteCoderankDir, CODERANK_FILENAME);
            return new Git(
                username,
                token,
                repo,
                branch,
                coderankDir,
                repoDir,
                remoteCoderankDir,
                remoteCoderankFile
            );
        }
        return null;
    }

    static async login_context(
        context: ExtensionContext,
        saveCredentials: boolean,
        callback: (git: Git) => void | Promise<void>
    ): Promise<void> {
        const git = await Git.login(context, saveCredentials);
        if (git !== null) {
            const callbackResult = callback(git);

            if (callbackResult instanceof Promise) {
                await callbackResult;
            }

            await git.teardown();
            if (saveCredentials) {
                await git.saveCredentials(context);
            }
        }
    }

    async cloneRepo(): Promise<void> {
        await fs.rm(this.repoDir, { recursive: true, force: true });
        const cloneUrl = `https://${this.username}:${this.token}@github.com/${this.username}/${this.repo}.git`;
        const git = simpleGit(this.coderankDir);
        await git.clone(cloneUrl, this.repoDir);
        const status = await git.status();
        this.branch = status.current;
        await fs.mkdir(this.remoteCoderankDir, { recursive: true });
        await fs.writeFile(path.join(this.remoteCoderankDir, "README.md"), getREADMEContent());
    }

    async pushRepo(message?: string): Promise<void> {
        message = message || getDate();
        const git = simpleGit(this.repoDir);
        await git.add("./*");
        await git.commit(`coderank auto-commit: ${message}`);
        await git.push();
    }

    async saveCredentials(context: ExtensionContext): Promise<void> {
        await context.secrets.store("githubUser", this.username);
        await context.secrets.store("githubPAT", this.token);
        await context.secrets.store("githubRepo", this.repo);
    }

    async teardown(): Promise<void> {
        try {
            this.branch = null;
            await fs.rm(this.repoDir, { recursive: true, force: true });
        } catch (err) {
            window.showWarningMessage(
                `Warning: failed to remove ${this.repoDir}. This is not critical, but may cause issues when ${this.repo} is next cloned: ${err}`
            );
        }
    }

    get repoAndBranch(): string {
        return this.branch ? `${this.repo}/${this.branch}` : this.repo;
    }
}

export function getREADMEContent(): string {
    return `
The contents of this directory are automatically generated by the coderank extension: https://github.com/reidspreiter/coderank.git

Please do not modify the following files in this directory, as it may affect the functionality of the coderank extension:
- README.md
- coderank.json

While it is not recommended, additional files may be added to this directory if needed. Only the files listed above will be modified by the extension, and all others will be preserved.
    `;
}
